#include <cctype>
#include <cstdlib>
#include <dirent.h>
#include <fstream>
#include <sstream>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include "main.tpp"
#include "Response.hpp"

static const char *	get_reason_phrase(int http_code) {
	switch (http_code) {
		case 100: return "Continue";
		case 101: return "Switching Protocols";
		case 200: return "OK";
		case 201: return "Created";
		case 202: return "Accepted";
		case 204: return "No Content";
		case 301: return "Moved Permanently";
		case 302: return "Found";
		case 303: return "See Other";
		case 304: return "Not Modified";
		case 307: return "Temporary Redirect";
		case 308: return "Permanent Redirect";
		case 400: return "Bad Request";
		case 401: return "Unauthorized";
		case 403: return "Forbidden";
		case 404: return "Not Found";
		case 405: return "Method Not Allowed";
		case 408: return "Request Timeout";
		case 409: return "Conflict";
		case 411: return "Length Required";
		case 413: return "Payload Too Large";
		case 414: return "URI Too Long";
		case 415: return "Unsupported Media Type";
		case 418: return "I'm a teapot";
		case 429: return "Too Many Requests";
		case 500: return "Internal Server Error";
		case 501: return "Not Implemented";
case 502: return "Bad Gateway";
		case 503: return "Service Unavailable";
		case 504: return "Gateway Timeout";
		case 505: return "HTTP Version Not Supported";
		default: return "Unknown Status";
	}
}

// static bool	status_has_body(int http_code) {
// 	if ((http_code >= 100 && http_code < 200) || http_code == 204 || http_code == 304)
// 		return false;
// 	return true;
// }

static std::string	to_lower_copy(const std::string & input) {
	std::string out = input;
	for (std::string::size_type i = 0; i < out.size(); ++i)
		out[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(out[i])));
	return out;
}

static std::string	build_default_error_page(int http_code) {
	std::stringstream html;
	html << "<!DOCTYPE html>\n"
		<< "<html><head><meta charset=\"UTF-8\"><title>"
		<< http_code << " " << get_reason_phrase(http_code)
		<< "</title></head><body><h1>"
		<< http_code << " " << get_reason_phrase(http_code)
		<< "</h1></body></html>\n"
		<< "<!-- Default error page generated by my webserv -->";
	return html.str();
}

Response::Response(void): _server(0), _location(0), _cgi(0), _rewrite(0) {
	// log_info("Response constructor called");
}

Response::Response(int fd) : _server(0), _location(0), _cgi(0), _rewrite(0), _fd(fd) {
	// log_info("Response constructor with fd called");
}

Response::Response(const Response & other) {
	// log_info("Response copy constructor called");
	*this = other;
}

Response & Response::operator=(const Response & other) {
	// log_info("Response assignment operator called");
	this->_server = other._server;
	this->_location = other._location;
	this->_cgi = other._cgi;
	this->_rewrite = other._rewrite;
	this->_fd = other._fd;
	this->_response = other._response;
	this->_error_pages = other._error_pages;
	return *this;
}

Response::~Response(void) {
	// log_info("Response destructor called");
}

void	Response::clean_response(void) {
	_status_line.flush();
	_headers.flush();
	_response_body.flush();
	_response.clear();
}

void	Response::classic_http_hat(int http_code) {
	const std::string empty_body;
	log_debug<int>("Building response with HTTP code ", http_code);
	_status_line << "HTTP/1.1 " << http_code << " " << get_reason_phrase(http_code) << "\r\n";
}

void	Response::prepare_error_content(int http_code) {
	if (_error_pages.find(http_code) != _error_pages.end()) {
		if (access(_error_pages.at(http_code).c_str(), F_OK | R_OK) != -1) {
			std::ifstream	ifs(_error_pages.at(http_code).c_str());
			if (ifs.is_open()) {
				_response_body << ifs.rdbuf();;
				ifs.close();
				return ;
			}
			log_error("Error page is not open");
		}
		log_error("Cannot access error page: " + _error_pages.at(http_code));
	}
	log_info("No pages found for this error");
	log_debug<size_t>("Size of error pages", _error_pages.size());
	_response_body << build_default_error_page(http_code);
	return ;
}

void	Response::prepare_error_response(int http_code) {
	classic_http_hat(http_code);
	prepare_error_content(http_code);
}

void	Response::prepare_auto_index(const std::string &uri, const std::string &dir_path) {
	DIR *dir = opendir(dir_path.c_str());
	if (dir == NULL) { prepare_error_response(500); return ; }
	classic_http_hat(200);
	_response_body << "<!DOCTYPE html><html><head><title>Index of " 
		<< uri << "</title></head><body>"
		<< "<h1>Index of " << uri << "</h1>"
		<< "<hr><pre>" ;

	struct dirent *entry;
	while ((entry = readdir(dir)) != NULL) {
		std::string name = entry->d_name;
		if (name == ".") { continue ; }
		std::string display_name = name;
		if (entry->d_type == DT_DIR) { display_name += "/"; }
		std::string href;
		if (name == "..") { href = name; }
		else {
			std::string base_uri = uri;
			if (!base_uri.empty() && base_uri[base_uri.size() - 1] != '/') { base_uri += "/"; }
			href = base_uri + name;
			if (entry->d_type == DT_DIR) { href += "/"; }
		}
		_response_body << "<a href=\"" << href << "\">" << display_name << "</a>" << std::endl; 
	}
	closedir(dir);
	_response_body << "</pre><hr></body></html>";
}

/// Prepare content of response

client_status	Response::prepare_redirect(const std::string & uri) {
	log_info("Preparing response for redirect");
	classic_http_hat(_rewrite->error_code);

	const std::string & replacm = _rewrite->replacement;
	add_to_headers<std::string>("Location", replacm.substr(0, replacm.find("/$1")) + uri.substr(uri.find(_location->path) + _location->path.size()));
	return SENDING_RESPONSE;
}

client_status 	Response::prepare_post(const std::string &uri, const std::string &body, const std::string &body_type) {
	log_info("Preparing response for POST");
	if (body.size() > _server->client_max_body_size) {
		log_debug<size_t>("Body size is", body.size());
		log_debug<size_t>("Client max body size is", _server->client_max_body_size);
		prepare_error_response(413);
		return SENDING_RESPONSE;
	}
	std::string file_path = uri.substr(uri.find(_location->path) + _location->path.size(), uri.find("?"));
	log_debug<std::string>("File path for POST request", file_path);
	log_debug<std::string>("with body type", body_type);
	if (body_type.substr(0, body_type.find(";")) == "multipart/form-data") {
		if (_location->upload_auth == false) {
			prepare_error_response(403);
			return SENDING_RESPONSE;
		}
		file_path = _location->upload_path + file_path;
		log_warning<std::string>("Trying to create new file", file_path);
		std::ofstream	new_file(file_path.c_str());
		if (new_file.fail()) {
			prepare_error_response(500);
			return SENDING_RESPONSE;
		}
		new_file << body;
		new_file.close();
		classic_http_hat(201);
		return SENDING_RESPONSE;
	}
	else {
		log_info("So not an upload");
		if (access(file_path.c_str(), F_OK | W_OK) == -1) {
		// modify file
			prepare_error_response(403);
			return SENDING_RESPONSE;
		}
	}
	classic_http_hat(200);
	return SENDING_RESPONSE;
}

client_status	Response::prepare_delete(const std::string &uri) {
	std::string file_path = uri.substr(0, uri.find("?"));
	file_path = _location->root + file_path.substr(file_path.find(_location->path) + _location->path.size());
	if (access(file_path.c_str(), F_OK) == -1) {
		prepare_error_response(404);
		return SENDING_RESPONSE;
	}
	if (remove(file_path.c_str()) == -1) {
		prepare_error_response(500);
		return SENDING_RESPONSE;
	}
	classic_http_hat(200);
	return SENDING_RESPONSE;
}

client_status	Response::prepare_get(const std::string &uri) {
	std::string file_path = uri.substr(0, uri.find("?"));
	file_path = file_path.substr(file_path.find(_location->path) + _location->path.size());
	if (file_path[0] == '/')
		file_path.erase(0, 1);
	file_path = _location->root + file_path;
	log_debug<std::string>("Prepared file path for GET: ", file_path);
	if (file_path.at(file_path.size() - 1) == '/') {
		if (_location->autoindex == true) {
			prepare_auto_index(uri.substr(0, uri.find("?")), file_path);
			return SENDING_RESPONSE;
		}
		if (_location->index_files.empty()) {
			prepare_error_response(403);
			return SENDING_RESPONSE;
		}
		for (std::set<std::string>::const_iterator it = _location->index_files.begin(); it != _location->index_files.end(); ++it) {
			std::string index_file = file_path + *it;
			if (access(index_file.c_str(), F_OK) != -1) {
				file_path = index_file;
				break ;
			}
		}
	}
	if (access(file_path.c_str(), F_OK) == -1) {
		prepare_error_response(404);
		return SENDING_RESPONSE;
	}
	if (access(file_path.c_str(), R_OK) == -1) {
		prepare_error_response(403);
		return SENDING_RESPONSE;
	}
	std::ifstream	ifs(file_path.c_str());
	if (ifs.is_open()) {
		classic_http_hat(200);
		add_to_headers<std::string>("Content-type", get_content_type(file_path));
		_response_body << ifs.rdbuf();
		ifs.close();
		return SENDING_RESPONSE;
	}
	else {
		prepare_error_response(500);
		return SENDING_RESPONSE;
	}
}

bool	Response::is_raw_cgi(const std::string &cgi_answer) {
	if (cgi_answer.find("Status: ") < cgi_answer.find("\r\n"))
		return false;
	return true;
}

void	Response::prepare_cgi(const std::string &cgi_answer) {
	// log_info("Preparing response after CGI");
	// log_debug<std::string>("CGI output", cgi_answer);
	
	if (is_raw_cgi(cgi_answer) == true) {
		_status_line << "HTTP/1.1 200 CGI OK\r\n";
		add_to_headers<std::string>("Content-type", "application/octet-stream");
		_response_body << cgi_answer;
		return ;
	}

	std::stringstream output(cgi_answer);
	std::string line;
	// SUPPOSING CGI ARE HTTP ENCODED
	while (std::getline(output, line)) {
		if (line == "\r")
			break ; // end of headers
		if (line.find("Status: ") != std::string::npos) {
			classic_http_hat(std::atoi(line.substr(line.find("Status: ") + 8).c_str()));
		}
		else {
			_headers << line << "\r\n";
		}
	}
	_response_body << output.rdbuf();
}


/// New function for new organisation -> too much maybe?


void	Response::setErrorPages(const std::map<int, std::string> &error_pages) {
	_error_pages = error_pages;
}

bool Response::finalize_response(std::string co_status) {
	add_to_headers<size_t>("Content-Length", _response_body.str().size());
	add_to_headers<std::string>("Connection", co_status);
	_response = _status_line.str() + _headers.str() + "\r\n" + _response_body.str();
	_status_line.str(""); _headers.str(""); _response_body.str("");
	return true;
}

std::string	Response::get_content_type(const std::string & file_path) const {
	std::string::size_type dot = file_path.find_last_of('.');
	if (dot == std::string::npos)
		return "application/octet-stream";

	std::string ext = to_lower_copy(file_path.substr(dot));
	if (ext == ".html" || ext == ".htm") return "text/html; charset=utf-8";
	if (ext == ".css") return "text/css; charset=utf-8";
	if (ext == ".js") return "application/javascript; charset=utf-8";
	if (ext == ".json") return "application/json; charset=utf-8";
	if (ext == ".txt") return "text/plain; charset=utf-8";
	if (ext == ".xml") return "application/xml; charset=utf-8";
	if (ext == ".svg") return "image/svg+xml";
	if (ext == ".png") return "image/png";
	if (ext == ".jpg" || ext == ".jpeg") return "image/jpeg";
	if (ext == ".gif") return "image/gif";
	if (ext == ".ico") return "image/x-icon";
	if (ext == ".webp") return "image/webp";
	if (ext == ".pdf") return "application/pdf";
	if (ext == ".wasm") return "application/wasm";
	return "application/octet-stream";
}

client_status Response::send_response(void) {
	// log_warning<std::string>("Sending response to client fd ", _response);
	if (_response.empty()) {
		log_error("Response is empty, nothing to send");
		return WAITING;
	}
	ssize_t	bytes_send = send(_fd, _response.c_str(), _response.size(), MSG_NOSIGNAL);
	if (bytes_send == -1) {
		log_error(strerror(errno));
		log_error("Failed to send response to client");
		return WAITING;
	}
	// log_debug<size_t>("Response size", _response.size());
	// log_debug<ssize_t>("Bytes send", bytes_send);
	if (static_cast<size_t>(bytes_send) == _response.size())
		return WAITING;
	size_t	by = static_cast<size_t>(bytes_send);
	// log_debug<size_t>("Size_t bytes", by);
	_response.erase(0, by);
	return SENDING_RESPONSE;
}
