#include <sstream>
#include <sys/socket.h>
#include <cctype>
#include "main.tpp"
#include "Response.hpp"

static const char *	get_reason_phrase(int http_code) {
	switch (http_code) {
		case 100: return "Continue";
		case 101: return "Switching Protocols";
		case 200: return "OK";
		case 201: return "Created";
		case 202: return "Accepted";
		case 204: return "No Content";
		case 301: return "Moved Permanently";
		case 302: return "Found";
		case 303: return "See Other";
		case 304: return "Not Modified";
		case 307: return "Temporary Redirect";
		case 308: return "Permanent Redirect";
		case 400: return "Bad Request";
		case 401: return "Unauthorized";
		case 403: return "Forbidden";
		case 404: return "Not Found";
		case 405: return "Method Not Allowed";
		case 408: return "Request Timeout";
		case 409: return "Conflict";
		case 411: return "Length Required";
		case 413: return "Payload Too Large";
		case 414: return "URI Too Long";
		case 415: return "Unsupported Media Type";
		case 418: return "I'm a teapot";
		case 429: return "Too Many Requests";
		case 500: return "Internal Server Error";
		case 501: return "Not Implemented";
		case 502: return "Bad Gateway";
		case 503: return "Service Unavailable";
		case 504: return "Gateway Timeout";
		case 505: return "HTTP Version Not Supported";
		default: return "Unknown Status";
	}
}

static bool	status_has_body(int http_code) {
	if ((http_code >= 100 && http_code < 200) || http_code == 204 || http_code == 304)
		return false;
	return true;
}

static std::string	to_lower_copy(const std::string & input) {
	std::string out = input;
	for (std::string::size_type i = 0; i < out.size(); ++i)
		out[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(out[i])));
	return out;
}

static std::string	build_default_error_page(int http_code) {
	std::stringstream html;
	html << "<!DOCTYPE html>\n"
		<< "<html><head><meta charset=\"UTF-8\"><title>"
		<< http_code << " " << get_reason_phrase(http_code)
		<< "</title></head><body><h1>"
		<< http_code << " " << get_reason_phrase(http_code)
		<< "</h1></body></html>\n"
		<< "<!-- Default error page generated by my webserv -->";
	return html.str();
}

Response::Response(void) {
	// log_info("Response constructor called");
}

Response::Response(int fd) : _fd(fd) {
	// log_info("Response constructor with fd called");
}

Response::Response(const Response & other) {
	// log_info("Response copy constructor called");
	*this = other;
}

Response & Response::operator=(const Response & other) {
	// log_info("Response assignment operator called");
	this->_fd = other._fd;
	this->_response = other._response;
	return *this;
}

Response::~Response(void) {
	// log_info("Response destructor called");
}

void	Response::clean_fd(void) {
	_fd = -1;
}

void	Response::setErrorPages(const std::map<int, std::string> &error_pages) {
	_error_pages = error_pages;
}

bool Response::build_response(const std::string content, const int http_code, std::string co_status) {
	const std::string empty_body;
	log_debug<int>("Building response with HTTP code ", http_code);
	_response_body << (status_has_body(http_code) ? content : empty_body);
	log_debug<std::string>("Content is", _response_body.str());

	if (_response_body.str().empty() && http_code >= 400 && http_code <= 599) {
		log_error("an error has been detected");
		_response_body << build_default_error_page(http_code);
		add_to_headers("Content-Type", "text/html; charset=utf-8");
	}

	_status_line << "HTTP/1.1 " << http_code << " " << get_reason_phrase(http_code) << "\r\n";

	add_to_headers<size_t>("Content-Length", _response_body.str().size());
	add_to_headers<std::string>("Connection", co_status);
	_response = _status_line.str() + _headers.str() + "\r\n" + _response_body.str();
	_status_line.str(""); _headers.str(""); _response_body.str("");
	return true;
}

void	Response::build_redirect(const std::string & uri, const std::string & location_path, const std::string & replacement) {
	add_to_headers<std::string>("Location", replacement.substr(0, replacement.find("/$1")) + uri.substr(uri.find(location_path) + location_path.size()));
}

std::string	Response::get_content_type(const std::string & file_path) const {
	std::string::size_type dot = file_path.find_last_of('.');
	if (dot == std::string::npos)
		return "application/octet-stream";

	std::string ext = to_lower_copy(file_path.substr(dot));
	if (ext == ".html" || ext == ".htm") return "text/html; charset=utf-8";
	if (ext == ".css") return "text/css; charset=utf-8";
	if (ext == ".js") return "application/javascript; charset=utf-8";
	if (ext == ".json") return "application/json; charset=utf-8";
	if (ext == ".txt") return "text/plain; charset=utf-8";
	if (ext == ".xml") return "application/xml; charset=utf-8";
	if (ext == ".svg") return "image/svg+xml";
	if (ext == ".png") return "image/png";
	if (ext == ".jpg" || ext == ".jpeg") return "image/jpeg";
	if (ext == ".gif") return "image/gif";
	if (ext == ".ico") return "image/x-icon";
	if (ext == ".webp") return "image/webp";
	if (ext == ".pdf") return "application/pdf";
	if (ext == ".wasm") return "application/wasm";
	return "application/octet-stream";
}

client_status Response::send_response(void) {
	log_warning<std::string>("Sending response to client fd ", _response);
	if (_response.empty()) {
		log_error("Response is empty, nothing to send");
		return WAITING;
	}
	ssize_t	bytes_send = send(_fd, _response.c_str(), _response.size(), MSG_NOSIGNAL);
	if (bytes_send == -1) {
		log_error("Failed to send response to client");
		return WAITING;
	}
	log_debug<size_t>("Response size", _response.size());
	log_debug<ssize_t>("Bytes send", bytes_send);
	if (static_cast<size_t>(bytes_send) == _response.size())
		return WAITING;
	size_t	by = static_cast<size_t>(bytes_send);
	log_debug<size_t>("Size_t bytes", by);
	_response.erase(0, by);
	return SENDING_RESPONSE;
}
