# Server to serv file
server {
	listen 8080;

	error_pages 403 var/www/errors/403.html;
	error_pages 404 var/www/errors/404.html;

	client_max_body_size	10K;

	location / {
		allow_methods GET;

		root var/www/html/;
		autoindex off; // Pas de sens avec le truc du bas
		index index.html index.htm;
	}

	location /cgi-bin {
		rewrite ^/test.pl$ http://127.0.0.1:8082/ redirect;
		rewrite ^/test.py$ http://127.0.0.1:8082/ redirect;
		rewrite ^/test.sh$ http://127.0.0.1:8082/ redirect;
	}

	location /upload {
		allow_methods GET;
		root var/upload/;
	}
}

# Server to upload
server {
	listen 8081;

	error_pages 413 var/www/errors/413.html;

	client_max_body_size	100M;

	location / {
		allow_methods POST DELETE;

		upload_auth on;
		upload_path var/upload/;
	}
}

# Server to execute CGI
server {
	listen 8082;

	error_pages 500 var/www/errors/internal_error.html;
	error_pages 501 var/www/errors/internal_error.html;

	location / {
		allow_methods GET POST;

		cgi .pl	/usr/bin/perl;
		cgi .py	/Users/jbl/Desktop/42cursus/conda/bin/python3 POST;
		cgi .sh	/bin/sh GET;

		root var/cgi-bin/;
		autoindex on;
	}
}
